### ISSUE TITLE
Private event URLs too easy to guess

### ISSUE THREAD

**Issue by HazardCreative** [FPVScores/FPVScores#17]
Looks like the URL is just `/events/[database id]`. This should be something a little harder to guess if an event is marked as private.

**Comment by JesseFPV** [comment]
The idea was not really that it would be impossible to find but only not displayed on public listings. Thats why I did not used something like a random slug.

I could understand you don't want an event listed but I'm not sure if its necessary to really make it unfindable in any way. You can always not publish the event.

Do you think it would be needed to have the URL secret?

**Comment by JesseFPV** [comment]
Fixed on coming update.
