### ISSUE TITLE
Current version compatibility

### ISSUE THREAD

**Issue by HazardCreative** [FPVScores/FPVScores#19]
RH's current version data export doesn't match website's expectations. Getting this (many times) on upload:

`Warning: Undefined array key "note" in /var/www/vhosts/fpvscores.com/api.fpvscores.com/API/rh/0.0.1/functions/import.php on line 174`

Uploaded heats are not named.

FPVScores page: https://fpvscores.com/events/16/results
RH database: [2023-09-05 Whoops at Beta api 41.zip](https://github.com/FPVScores/FPVScores/files/12614347/2023-09-05.Whoops.at.Beta.api.41.zip)

**Comment by JesseFPV** [comment]
Fixed
