### ISSUE TITLE
Include "show more" only if necessary

### ISSUE THREAD

**Issue by HazardCreative** [FPVScores/FPVScores#23]
If the "show more" link takes up as much space as simply displaying the content, just show the content. For example, Round 1 is basically the same space but now it's extra clicks every time:

![image](https://github.com/FPVScores/FPVScores/assets/7169527/85b8ed82-63dd-457c-9f6d-ccf7a1a89ace)

There might be a higher threshold for this, too, such as hiding a minimum of 3 items.

**Comment by JesseFPV** [comment]
Fixed in next update
