### ISSUE TITLE
"Event totals" not consitent with RH usage

### ISSUE THREAD

**Issue by HazardCreative** [FPVScores/FPVScores#29]
RH provides "Event totals" which tally up the entire event's flying together. This is often not valid for comparisons or ranking and should not be shown prominently on FPVscores—if shown at all. However, use of the same terminology for the opening results page implies some kind of connection to this data.

If the intent is to show RH's event totals, they should not appear first.

**Comment by JesseFPV** [comment]
Event totals are not shown on the results page (or on any other page). Only class totals (summary) is, its shown by the title that the table is about the class. Do you think it needs another way to display to be not confusing?

<img width="1306" alt="Screenshot 2023-09-19 at 21 54 06" src="https://github.com/FPVScores/FPVScores/assets/42770753/eecff26d-57a4-407a-ae26-76d3412d8144">

**Comment by JesseFPV** [comment]
Changed titel of pills and page to 'All Classes'
