### ISSUE TITLE
"Show More" not working on class summary tabs

### ISSUE THREAD

**Issue by HazardCreative** [FPVScores/FPVScores#32]
- Load race results
- Visit any race class tab (with sufficient data)
- Use "Show more"
- Nothing happens on page.
- `toggle_leaderboard tableid: lbtable_25 heightcalc: 450` (or similar) appears in JS console

Example: https://fpvscores.com/events/bl943kev93/results

**Comment by HazardCreative** [comment]
If it's helpful, I just noticed that the corresponding table on the "All classes" tab expands/contracts when you click the link in the tab page.

**Comment by JesseFPV** [comment]
Fixed on live
