### ISSUE TITLE
Past events list sorted oldest to newest

### ISSUE THREAD

**Issue by HazardCreative** [FPVScores/FPVScores#34]
In event manager.
Expectation is most recent events first.

![image](https://github.com/FPVScores/FPVScores/assets/7169527/475f1c2c-8884-4735-89fc-bdbdd685ed99)

**Comment by JesseFPV** [comment]
Fixed on live

**Comment by JesseFPV** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TestTemplate](https://trello.com/c/d5GgEEaH/1-testtemplate)
