### ISSUE TITLE
IMPROVEMENT: Password requirements

### ISSUE THREAD

**Issue by StarrrLiteNL** [FPVScores/FPVScores#7]
6-19 characters is quite low these days, especially with the profileration of password managers.
It also didn't seem to accept a good range of special characters, and I had to re-roll my random password a couple of times to make it a valid password.

**Comment by JesseFPV** [comment]
Already changed to max of 64 chars. Have to look into special characters. I know !_# should work already

**Comment by JesseFPV** [comment]
Added ()
