### ISSUE TITLE
BUG: Language selection does not seem to work

### ISSUE THREAD

**Issue by StarrrLiteNL** [FPVScores/FPVScores#9]
The language selector in the top right, next to the profile picture, does not seem to change the displayed language.

Browser: Google Chrome Version 116.0.5845.141 (Official Build) (64-bit)
OS: Windows 11

![image](https://github.com/FPVScores/FPVScores/assets/17098554/49e2bacc-d81f-4034-abc9-f8981fd543c5)

**Comment by JesseFPV** [comment]
Function was not build in yet and should be hidden on release. Will hide it and add it as feature request.

**Comment by JesseFPV** [comment]
Hidden on new version.
